on:
  push:
    branches:
      - main

name: release

jobs:
  release-build-push:
    uses: Primoxo/workflows/.github/workflows/release-build-push.yml@main
    with:
      target_branch: main
      image_name: 'primoxo/release-please'