name: deploy

on:
  push:
    tags:
      - 'STAGING'
      - 'PRODUCTION'

jobs:
  deploy-staging:
    # this workflows uses conditionals to merge deployment for staging and prod into a single file (and to branch based on tag number)
    # alternatively two separate workflow files can be implemented with triggers on tags `STAGING` and `PRODUCTION`, respectively
    if: ${{ github.event.ref == 'refs/tags/STAGING' }}
    uses: MeKo-Tech/workflows/.github/workflows/deploy-branch.yml@main
    with:
      source_ref: ${{ github.event.ref }}
      target_branch: deployed_staging         # name of the target deploy branch (target for force-push)
      image_validate: false                   # do not check whether docker image exists before release (not required for deplyoment)
      image_name: 'primoxo/release-please'
      delete_invalid_tags: true               # delete tag `STAGING` from remote in case it does not refer to a valid release

  deploy-production:
    if: ${{ github.event.ref == 'refs/tags/PRODUCTION' }}
    uses: MeKo-Tech/workflows/.github/workflows/deploy-branch.yml@main
    with:
      source_ref: ${{ github.event.ref }}
      target_branch: deployed_production
      image_validate: false
      image_name: 'primoxo/release-please'
      delete_invalid_tags: true