on:
  workflow_call:
    inputs:
      ssh_host:
        type: string
        required: true
        description: hostname of the remote docker host
      ssh_user:
        type: string
        required: true
        description: username used to authenticate to remote docker host
      compose_file:
        type: string
        required: true
        description: path to docker-compose file relative to repository root
      compose_project_name:
        type: string
        required: true
        description: name of the docker compose project
    secrets:
      ssh_private_key:
        required: true
        description: ssh private key used to authenticate to remote docker host
      env_file_data:
        required: true
        description: .env file holding application configuration. Check docker-compose file for available variables.

jobs:
  docker-compose-up:
    uses: ./.github/workflows/docker-compose-up.yml
    with:
      ssh_host: ${{ inputs.ssh_host }}
      ssh_user: ${{ inputs.ssh_user }}
      compose_file: ${{ inputs.compose_file }}
      compose_project_name: ${{ inputs.compose_project_name }}
    secrets:
      ssh_private_key: ${{ secrets.ssh_private_key }}
      env_file_data: ${{ secrets.env_file_data }}