# This action tags the commit with a Semver number and creates a GitHub release wich references this tag
#
# required permissions:
#   contents: write

name: release

on:
  workflow_call:
    inputs:
      token: 
        type: string
        description: 'Access token used by the workflow. This workflow will not trigger any subsequent workflow runs in case the default GITHUB_TOKEN is used'
        default: ${{ secrets.GITHUB_TOKEN }}
      config_file:
        type: string
        description: 'path to release-please config file'
        default: release-please-config.json
      manifest_file:
        type: string
        description: 'path to release-please manifest file'
        default: .release-please-manifest.json

    outputs:
      release_created: 
        description: 'true if a release was created by this workflow, false otherwise'
        value: ${{ jobs.release.outputs.release_created }}
      release_semver:
        description: 'Semver number of the release created by this workflow. Empty in case no release was created'
        value: ${{ jobs.release.outputs.release_semver }}

jobs:
  release:
    runs-on: ubuntu-latest
    # permissions take only effect for authentication with GITHUB_TOKEN
    permissions:
      contents: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }} 
      release_semver: '${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}'
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:  
          token: ${{ inputs.token }}
          config-file: ${{ inputs.config_file }}
          manifest-file: ${{ inputs.manifest_file }}
          skip-github-pull-request: true     # configure release-please action to only create releases